const mongoose= require('mongoose');
const receiptSchema= mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    price:{
        type:Number,
        required:true
    },
    quantity:{
        type:Number,
        required:true
    },
    total:{
        type:Number,
        required:true
    },
    date:{
        type:Date,
        default:Date.now
    },
    userId:{
        type:String,
        required:true
    },
    products:[
        {
            productId:{
                type:String
            },
            quantity:{
                type:Number,
                default:1
            }
        }
    ]
})
module.exports=mongoose.model('Receipt',receiptSchema);