const mongoose = require('mongoose');
const userSchema=mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    password:{
        type:String,
        required:true
    },
    birthday:{
        type:Date,
        required:true
    },
    gender:{
        type:String,
        required:true
    },
    phone:{
        type:String,
        required:true
    },
    address:{
        type:String,
    },
    image:{
        data:Buffer,
        contentType:String
    },
    role:{
        type:String,
        default:'user'
    }
})
module.exports=mongoose.model('User',userSchema);